[package]
name = "weylus"
version = "0.10.0"
authors = ["HMH <henry@freedesk.net>"]
license = "AGPL-3.0-or-later"
edition = "2018"
description = "Use your iPad or Android tablet as graphic tablet."

[dependencies]
hyper = "^0.13"
url = "^2.2"
tokio = { version = "0.2", features = ["full"] }
handlebars = "^3.5"
websocket = "^0.26"
autopilot = "0.4.0"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
tracing = "^0.1"
tracing-subscriber = "^0.2"
bitflags = "^1.2"
image_autopilot = { package = "image", version = "0.22.5" }
image = "^0.23"
fltk = { version = "^0.16", features = ["no-pango"]}
qrcode = "0.12.0"
percent-encoding = "2.1.0"
toml = "^0.5"
structopt = "^0.3"
dirs = "^3.0"

[build-dependencies]
cc = "^1.0"
num_cpus = "^1.13"

[target.'cfg(target_os = "linux")'.dependencies]
dbus = "^0.9"
gstreamer = "^0.16"
gstreamer-app = { version = "^0.16", features = ["v1_10"] }
gstreamer-video = "^0.16"

[target.'cfg(not(target_os = "windows"))'.dependencies]
pnet = "^0.26"

[features]
bench = []
ffmpeg-system = []
va-static = []

[package.metadata.bundle]
name = "Weylus"
identifier = "io.github.h-m-h.weylus"

[package.metadata.deb]
name = "Weylus"
depends = "$auto"
section = "graphics"
priority = "optional"
assets = [
    ["target/release/weylus", "usr/bin/weylus", "755"],
    ["weylus.desktop", "usr/share/applications/weylus.desktop", "755"],
    ["Readme.md", "usr/share/doc/weylus/README", "644"],
]

[profile.release]
lto = true
opt-level = 3
